name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
        matrix: { dir: ['gcribbage-lib'] }
    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ${{ matrix.dir }}
      run: cargo build --verbose
    - name: Run tests
      working-directory: ${{ matrix.dir }}
      run: cargo test --verbose
